traefik:
  image:
    pullPolicy: Always

  deployment:
    revisionHistoryLimit: 0

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress

  providers:
    kubernetesCRD:
      enabled: false
    kubernetesIngress:
      enabled: true
      ingressClass: ingress

  ports:
    web:
      forwardedHeaders:
        insecure: true
    websecure:
      forwardedHeaders:
        insecure: true

  topologySpreadConstraints:
    - topologyKey: topology.kubernetes.io/zone
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      minDomains: 3
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
    - topologyKey: kubernetes.io/hostname
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: traefik

  logs:
    general:
      format: json
      level: "INFO"
      noColor: true
    access:
      enabled: true
      format:  json

  additionalArguments:
    # Allow accessing the dashboard at http://localhost:9000/dashboard/ when using port-forward
    - --api.insecure=true
    # Skip TLS verification for backends with self-signed certificates
    - --serversTransport.insecureSkipVerify=true
    # Force Traefik to set a hostname on the status field of Ingress resources to stop Argocd from marking ingress
    # resources as "Progressing".
    # https://github.com/argoproj/argo-cd/issues/14607#issuecomment-1966557671
    - --providers.kubernetesingress.ingressendpoint.hostname=ingress.example.org

  service:
    enabled: true
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 100Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
