apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: traefik
spec:
  serviceRef:
    name: traefik
    port: 443
  targetType: ip
  targetGroupARN: {{ .Values.targetGroupArn }}
